language: ruby
sudo: false

rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2
- 2.1
- 2.0
- 1.9.3
- jruby-head
- jruby-9.1.15.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.1
    - rvm: 2.0
    - rvm: 1.9.3

